const { DataTypes } = require('sequelize');
const sequelize = require('../config/database');

const PurchaseRequest = sequelize.define('PurchaseRequest', {
  id: {
    type: DataTypes.INTEGER,
    primaryKey: true,
    autoIncrement: true
  },
  prNumber: {
    type: DataTypes.STRING,
    unique: true,
    allowNull: true // Allow null and handle in hook
  },
  itemId: {
    type: DataTypes.INTEGER,
    allowNull: false,
    references: {
      model: 'items',
      key: 'id'
    }
  },
  warehouseId: {
    type: DataTypes.INTEGER,
    allowNull: false,
    references: {
      model: 'warehouses',
      key: 'id'
    }
  },
  requestedQuantity: {
    type: DataTypes.INTEGER,
    allowNull: false,
    validate: {
      min: 1
    }
  },
  urgencyLevel: {
    type: DataTypes.ENUM('low', 'medium', 'high', 'urgent'),
    defaultValue: 'medium'
  },
  reason: {
    type: DataTypes.ENUM('low_stock', 'out_of_stock', 'manual_request', 'reorder_point'),
    defaultValue: 'low_stock'
  },
  status: {
    type: DataTypes.ENUM('pending', 'approved', 'rejected', 'converted_to_po'),
    defaultValue: 'pending'
  },
  notes: {
    type: DataTypes.TEXT,
    allowNull: true
  },
  requestedById: {
    type: DataTypes.INTEGER,
    allowNull: false,
    references: {
      model: 'users',
      key: 'id'
    }
  },
  approvedById: {
    type: DataTypes.INTEGER,
    allowNull: true,
    references: {
      model: 'users',
      key: 'id'
    }
  },
  approvedAt: {
    type: DataTypes.DATE,
    allowNull: true
  },
  isAutoGenerated: {
    type: DataTypes.BOOLEAN,
    defaultValue: false
  },
  preferredSupplierId: {
    type: DataTypes.INTEGER,
    allowNull: true,
    references: {
      model: 'suppliers',
      key: 'id'
    }
  }
}, {
  timestamps: true,
  tableName: 'purchase_requests',
  hooks: {
    beforeCreate: async (pr, options) => {
      // Generate prNumber if not set
      if (!pr.prNumber) {
        try {
          // Get the current count to generate sequential number
          const count = await PurchaseRequest.count({
            transaction: options.transaction
          });
          pr.prNumber = `PR${String(count + 1).padStart(6, '0')}`;
          console.log('🔢 Generated PR Number in hook:', pr.prNumber);
        } catch (error) {
          console.error('❌ Error in beforeCreate hook:', error);
          // Fallback to timestamp-based number
          pr.prNumber = `PR${Date.now()}`;
        }
      }
    }
  }
});

module.exports = PurchaseRequest;