const { DataTypes } = require('sequelize');
const sequelize = require('../config/database');

const PurchaseRequest = sequelize.define('PurchaseRequest', {
  id: {
    type: DataTypes.INTEGER,
    primaryKey: true,
    autoIncrement: true
  },
  prNumber: {
    type: DataTypes.STRING,
    unique: true,
    allowNull: true // Allow null and handle in hook
  },
  itemId: {
    type: DataTypes.INTEGER,
    allowNull: false,
    references: {
      model: 'items',
      key: 'id'
    }
  },
  warehouseId: {
    type: DataTypes.INTEGER,
    allowNull: false,
    references: {
      model: 'warehouses',
      key: 'id'
    }
  },
  requestedQuantity: {
    type: DataTypes.INTEGER,
    allowNull: false,
    validate: {
      min: 1
    }
  },
  urgencyLevel: {
    type: DataTypes.ENUM('low', 'medium', 'high', 'urgent'),
    defaultValue: 'medium'
  },
  reason: {
    type: DataTypes.ENUM('low_stock', 'out_of_stock', 'manual_request', 'reorder_point'),
    defaultValue: 'manual_request'
  },
  status: {
    type: DataTypes.ENUM('pending', 'approved', 'rejected', 'converted_to_po'),
    defaultValue: 'pending'
  },
  notes: {
    type: DataTypes.TEXT,
    allowNull: true
  },
  requestedById: {
    type: DataTypes.INTEGER,
    allowNull: false,
    references: {
      model: 'users',
      key: 'id'
    }
  },
  approvedById: {
    type: DataTypes.INTEGER,
    allowNull: true,
    references: {
      model: 'users',
      key: 'id'
    }
  },
  approvedAt: {
    type: DataTypes.DATE,
    allowNull: true
  },
  isAutoGenerated: {
    type: DataTypes.BOOLEAN,
    defaultValue: false
  },
  preferredSupplierId: {
    type: DataTypes.INTEGER,
    allowNull: true,
    references: {
      model: 'suppliers',
      key: 'id'
    }
  }
}, {
  timestamps: true,
  tableName: 'purchase_requests',
  hooks: {
    beforeCreate: async (pr, options) => {
      // Generate prNumber if not set
      if (!pr.prNumber) {
        try {
          // Use a more robust method to avoid duplicates during concurrent creation
          let attempts = 0;
          const maxAttempts = 10;
          
          while (attempts < maxAttempts) {
            // Get the highest existing PR number
            const lastPR = await PurchaseRequest.findOne({
              order: [['id', 'DESC']],
              attributes: ['prNumber'],
              transaction: options.transaction
            });
            
            let nextNumber = 1;
            if (lastPR && lastPR.prNumber) {
              const match = lastPR.prNumber.match(/PR(\d+)/);
              if (match) {
                nextNumber = parseInt(match[1]) + 1;
              }
            }
            
            const candidateNumber = `PR${String(nextNumber).padStart(6, '0')}`;
            
            // Check if this number already exists
            const existing = await PurchaseRequest.findOne({
              where: { prNumber: candidateNumber },
              transaction: options.transaction
            });
            
            if (!existing) {
              pr.prNumber = candidateNumber;
              console.log('🔢 Generated PR Number in hook:', pr.prNumber);
              break;
            }
            
            attempts++;
            // If we can't find a unique number, add random suffix
            if (attempts >= maxAttempts) {
              pr.prNumber = `PR${String(nextNumber + Math.floor(Math.random() * 1000)).padStart(6, '0')}`;
              console.log('🔢 Generated PR Number with random suffix:', pr.prNumber);
            }
          }
        } catch (error) {
          console.error('Error in beforeCreate hook:', error);
          // Fallback to timestamp-based number
          pr.prNumber = `PR${Date.now()}`;
        }
      }
    }
  }
});

module.exports = PurchaseRequest;