const { DataTypes } = require('sequelize');
const sequelize = require('../config/database');

const PurchaseOrder = sequelize.define('PurchaseOrder', {
  id: {
    type: DataTypes.INTEGER,
    primaryKey: true,
    autoIncrement: true
  },
  poNumber: {
    type: DataTypes.STRING,
    unique: true,
    allowNull: false
  },
  prId: {
    type: DataTypes.INTEGER,
    allowNull: true,
    references: {
      model: 'purchase_requests',
      key: 'id'
    }
  },
  supplierId: {
    type: DataTypes.INTEGER,
    allowNull: false,
    references: {
      model: 'suppliers',
      key: 'id'
    }
  },
  itemId: {
    type: DataTypes.INTEGER,
    allowNull: false,
    references: {
      model: 'items',
      key: 'id'
    }
  },
  warehouseId: {
    type: DataTypes.INTEGER,
    allowNull: false,
    references: {
      model: 'warehouses',
      key: 'id'
    }
  },
  orderedQuantity: {
    type: DataTypes.INTEGER,
    allowNull: false,
    validate: {
      min: 1
    }
  },
  unitPrice: {
    type: DataTypes.DECIMAL(10, 2),
    allowNull: false,
    validate: {
      min: 0
    }
  },
  totalAmount: {
    type: DataTypes.DECIMAL(12, 2),
    allowNull: false,
    validate: {
      min: 0
    }
  },
  status: {
    type: DataTypes.ENUM('draft', 'sent', 'acknowledged', 'delay_requested', 'partially_received', 'completed', 'cancelled'),
    defaultValue: 'draft'
  },
  expectedDeliveryDate: {
    type: DataTypes.DATE,
    allowNull: true
  },
  actualDeliveryDate: {
    type: DataTypes.DATE,
    allowNull: true
  },
  proposedDeliveryDate: {
    type: DataTypes.DATE,
    allowNull: true
  },
  terms: {
    type: DataTypes.TEXT,
    allowNull: true
  },
  notes: {
    type: DataTypes.TEXT,
    allowNull: true
  },
  createdById: {
    type: DataTypes.INTEGER,
    allowNull: false,
    references: {
      model: 'users',
      key: 'id'
    }
  },
  approvedById: {
    type: DataTypes.INTEGER,
    allowNull: true,
    references: {
      model: 'users',
      key: 'id'
    }
  },
  sentAt: {
    type: DataTypes.DATE,
    allowNull: true
  },
  approvedAt: {
    type: DataTypes.DATE,
    allowNull: true
  },
  isAutoGenerated: {
    type: DataTypes.BOOLEAN,
    defaultValue: false
  }
}, {
  timestamps: true,
  tableName: 'purchase_orders',
  hooks: {
    beforeCreate: async (po) => {
      if (!po.poNumber) {
        const count = await PurchaseOrder.count();
        po.poNumber = `PO${String(count + 1).padStart(6, '0')}`;
      }
      // Calculate total amount
      po.totalAmount = po.orderedQuantity * po.unitPrice;
    },
    beforeUpdate: async (po) => {
      if (po.changed('orderedQuantity') || po.changed('unitPrice')) {
        po.totalAmount = po.orderedQuantity * po.unitPrice;
      }
    }
  }
});

module.exports = PurchaseOrder;