import { useState, useEffect, useContext } from 'react';
import { AuthContext } from '../context/AuthContext';
import { fetchAllPurchaseOrders, approvePurchaseOrder, rejectPurchaseOrder, cancelPurchaseOrder, editPurchaseOrder } from '../api/purchaseOrderApi';
import { fetchSuppliers } from '../api/supplierApi';

const PurchaseOrder = () => {
  const { user } = useContext(AuthContext);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');

  // Data states
  const [purchaseOrders, setPurchaseOrders] = useState([]);
  const [suppliers, setSuppliers] = useState([]);

  // Filters
  const [filters, setFilters] = useState({
    status: '',
    supplierId: '',
    type: '' // Add type filter: 'auto', 'manual', or ''
  });

  // Modal states
  const [showDetailsModal, setShowDetailsModal] = useState(false);
  const [showEditModal, setShowEditModal] = useState(false);
  const [selectedPO, setSelectedPO] = useState(null);

  // Edit form state
  const [editForm, setEditForm] = useState({
    orderedQuantity: '',
    unitPrice: '',
    expectedDeliveryDate: '',
    notes: ''
  });

  const isAdmin = user?.role === 'admin';
  const isManager = user?.role === 'manager';
  const isWarehouse = user?.role === 'warehouse';
  
  // Access levels based on backend response
  const [accessLevel, setAccessLevel] = useState('none');
  
  // Determine user capabilities
  const canApprovePO = isAdmin;
  const canEditPO = isAdmin;
  const canCancelPO = isAdmin;
  const canApproveDelay = isAdmin || isManager; // ✅ FIXED: Manager can approve delays
  const canViewAll = isAdmin || isManager;
  const isLimitedAccess = isWarehouse;

  // Early return for testing - if user is not loaded yet
  if (!user) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600 mx-auto"></div>
          <p className="mt-4 text-gray-600">Loading user information...</p>
        </div>
      </div>
    );
  }

  console.log('PurchaseOrder component rendering, user:', user);
  console.log('Purchase orders data:', purchaseOrders);

  // Load data on component mount
  useEffect(() => {
    loadPurchaseOrders();
    loadSuppliers();

    // Listen for automatic PO creation events
    const handleAutomaticPRsCreated = (event) => {
      console.log('🔄 Automatic POs created, refreshing data...', event.detail);
      loadPurchaseOrders();
    };

    window.addEventListener('automaticPRsCreated', handleAutomaticPRsCreated);

    // Cleanup event listener
    return () => {
      window.removeEventListener('automaticPRsCreated', handleAutomaticPRsCreated);
    };
  }, []); // Empty dependency - runs once on mount

  // Reload when filters change
  useEffect(() => {
    // Always reload when filters change (including when cleared)
    loadPurchaseOrders();
  }, [filters]); // Reload whenever any filter changes

  const loadPurchaseOrders = async () => {
    setLoading(true);
    try {
      console.log('Loading purchase orders with filters:', filters);
      const response = await fetchAllPurchaseOrders(filters);
      console.log('Purchase orders response:', response);
      
      if (response.success) {
        setPurchaseOrders(response.data || []);
        setAccessLevel(response.accessLevel || 'none');
        console.log('Purchase orders loaded:', response.data?.length || 0);
        console.log('Access level:', response.accessLevel);
        
        // Debug: Check for automatic POs
        const autoPOs = response.data?.filter(po => po.isAutoGenerated) || [];
        console.log('🤖 Automatic POs found:', autoPOs.length);
        autoPOs.forEach(po => {
          console.log(`   - ${po.poNumber}: ${po.item?.name} (${po.unitPrice})`);
        });
      } else {
        setError('Failed to load purchase orders: ' + (response.message || 'Unknown error'));
        setPurchaseOrders([]);
      }
    } catch (err) {
      console.error('Load purchase orders error:', err);
      setError('Failed to load purchase orders: ' + (err.error || err.message || 'Unknown error'));
      setPurchaseOrders([]);
    } finally {
      setLoading(false);
    }
  };

  const loadSuppliers = async () => {
    try {
      console.log('🏪 Loading suppliers for PO page...');
      const response = await fetchSuppliers();
      console.log('🏪 Suppliers API response:', response);
      
      // Handle the correct API response format
      if (response.data && Array.isArray(response.data)) {
        setSuppliers(response.data);
        console.log('✅ Suppliers loaded for PO page:', response.data.length);
      } else if (Array.isArray(response)) {
        // Direct array response
        setSuppliers(response);
        console.log('✅ Suppliers loaded (direct array):', response.length);
      } else {
        console.warn('⚠️ Unexpected supplier response format:', response);
        setSuppliers([]);
      }
    } catch (err) {
      console.error('❌ Failed to load suppliers for PO page:', err);
      setSuppliers([]);
    }
  };

  // Clear messages
  useEffect(() => {
    if (error || success) {
      const timer = setTimeout(() => {
        setError('');
        setSuccess('');
      }, 5000);
      return () => clearTimeout(timer);
    }
  }, [error, success]);

  const openDetailsModal = (po) => {
    setSelectedPO(po);
    setShowDetailsModal(true);
  };

  // Admin-only PO actions
  const approvePO = async (poId) => {
    if (!canApprovePO) return;
    
    const confirmApproval = window.confirm('Are you sure you want to approve this purchase order?');
    if (!confirmApproval) return;
    
    try {
      setLoading(true);
      const response = await approvePurchaseOrder(poId, 'Approved by admin');
      
      if (response.success) {
        setSuccess('Purchase order approved and sent to supplier successfully');
        await loadPurchaseOrders();
      } else {
        setError('Failed to approve purchase order: ' + response.message);
      }
    } catch (err) {
      setError('Failed to approve purchase order: ' + (err.message || 'Unknown error'));
    } finally {
      setLoading(false);
    }
  };

  const rejectPO = async (poId) => {
    if (!canApprovePO) return;
    
    const reason = prompt('Please provide reason for rejection:');
    if (!reason) return;
    
    try {
      setLoading(true);
      const response = await rejectPurchaseOrder(poId, reason);
      
      if (response.success) {
        setSuccess('Purchase order rejected successfully');
        await loadPurchaseOrders();
      } else {
        setError('Failed to reject purchase order: ' + response.message);
      }
    } catch (err) {
      setError('Failed to reject purchase order: ' + (err.message || 'Unknown error'));
    } finally {
      setLoading(false);
    }
  };

  const editPO = async (poId) => {
    if (!canEditPO) return;
    
    // Find the PO to edit
    const poToEdit = purchaseOrders.find(po => po.id === poId);
    if (!poToEdit) {
      setError('Purchase order not found');
      return;
    }
    
    // Set up edit form with current values
    setSelectedPO(poToEdit);
    setEditForm({
      orderedQuantity: poToEdit.orderedQuantity.toString(),
      unitPrice: poToEdit.unitPrice.toString(),
      expectedDeliveryDate: poToEdit.expectedDeliveryDate ? new Date(poToEdit.expectedDeliveryDate).toISOString().split('T')[0] : '',
      notes: poToEdit.notes || ''
    });
    setShowEditModal(true);
  };

  const handleEditSubmit = async (e) => {
    e.preventDefault();
    
    if (!selectedPO) return;
    
    try {
      setLoading(true);
      
      const updateData = {
        orderedQuantity: parseInt(editForm.orderedQuantity),
        unitPrice: parseFloat(editForm.unitPrice),
        expectedDeliveryDate: editForm.expectedDeliveryDate || null,
        notes: editForm.notes
      };
      
      const response = await editPurchaseOrder(selectedPO.id, updateData);
      
      if (response.success) {
        setSuccess('Purchase order updated successfully');
        setShowEditModal(false);
        setSelectedPO(null);
        setEditForm({ orderedQuantity: '', unitPrice: '', expectedDeliveryDate: '', notes: '' });
        await loadPurchaseOrders();
      } else {
        setError('Failed to update purchase order: ' + response.message);
      }
    } catch (err) {
      setError('Failed to update purchase order: ' + (err.message || 'Unknown error'));
    } finally {
      setLoading(false);
    }
  };

  const cancelPO = async (poId) => {
    if (!canCancelPO) return;
    
    const reason = prompt('Please provide reason for cancellation:');
    if (!reason) return;
    
    try {
      setLoading(true);
      const response = await cancelPurchaseOrder(poId, reason);
      
      if (response.success) {
        setSuccess('Purchase order cancelled successfully');
        await loadPurchaseOrders();
      } else {
        setError('Failed to cancel purchase order: ' + response.message);
      }
    } catch (err) {
      setError('Failed to cancel purchase order: ' + (err.message || 'Unknown error'));
    } finally {
      setLoading(false);
    }
  };

  // Delay approval functions (Admin/Manager only)
  const approveDelay = async (poId) => {
    if (!canApproveDelay) return;
    
    const notes = prompt('Approval notes (optional):');
    
    try {
      setLoading(true);
      const response = await fetch(`/api/purchase-orders/${poId}/delay-approval`, {
        method: 'PUT',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${localStorage.getItem('token')}`
        },
        body: JSON.stringify({ action: 'approve', notes })
      });
      
      const data = await response.json();
      
      if (data.success) {
        setSuccess('Delay request approved successfully');
        await loadPurchaseOrders();
      } else {
        setError('Failed to approve delay: ' + data.message);
      }
    } catch (err) {
      setError('Failed to approve delay: ' + (err.message || 'Unknown error'));
    } finally {
      setLoading(false);
    }
  };

  const rejectDelay = async (poId) => {
    if (!canApproveDelay) return;
    
    const notes = prompt('Rejection reason (required):');
    if (!notes) return;
    
    try {
      setLoading(true);
      const response = await fetch(`/api/purchase-orders/${poId}/delay-approval`, {
        method: 'PUT',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${localStorage.getItem('token')}`
        },
        body: JSON.stringify({ action: 'reject', notes })
      });
      
      const data = await response.json();
      
      if (data.success) {
        setSuccess('Delay request rejected successfully');
        await loadPurchaseOrders();
      } else {
        setError('Failed to reject delay: ' + data.message);
      }
    } catch (err) {
      setError('Failed to reject delay: ' + (err.message || 'Unknown error'));
    } finally {
      setLoading(false);
    }
  };

  const getStatusBadge = (status) => {
    const statusConfig = {
      'draft': { color: 'bg-gray-100 text-gray-800', text: 'Draft' },
      'sent': { color: 'bg-blue-100 text-blue-800', text: 'Sent to Supplier' },
      'acknowledged': { color: 'bg-green-100 text-green-800', text: 'Acknowledged' },
      'delay_requested': { color: 'bg-orange-100 text-orange-800', text: 'Delay Requested' },
      'partially_received': { color: 'bg-yellow-100 text-yellow-800', text: 'Partially Received' },
      'completed': { color: 'bg-green-100 text-green-800', text: 'Completed' },
      'cancelled': { color: 'bg-red-100 text-red-800', text: 'Cancelled' }
    };

    const config = statusConfig[status] || { color: 'bg-gray-100 text-gray-800', text: status };
    
    return (
      <span className={`inline-flex px-2 py-1 text-xs font-semibold rounded-full ${config.color}`}>
        {config.text}
      </span>
    );
  };

  const getUrgencyBadge = (urgency) => {
    const urgencyConfig = {
      'low': { color: 'bg-gray-100 text-gray-800', text: 'Low' },
      'medium': { color: 'bg-blue-100 text-blue-800', text: 'Medium' },
      'high': { color: 'bg-yellow-200 text-yellow-700', text: 'High' },
      'urgent': { color: 'bg-red-100 text-red-800', text: 'Urgent' }
    };

    const config = urgencyConfig[urgency] || { color: 'bg-gray-100 text-gray-800', text: urgency };
    
    return (
      <span className={`inline-flex px-2 py-1 text-xs font-semibold rounded-full ${config.color}`}>
        {config.text}
      </span>
    );
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex justify-between items-center">
        <h1 className="text-2xl font-bold text-gray-900">Purchase Orders</h1>
        
        {/* Role-based header info removed */}
      </div>

      {/* Messages */}
      {error && (
        <div className="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded">
          {error}
        </div>
      )}
      {success && (
        <div className="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded">
          {success}
        </div>
      )}

      {/* Filters */}
      <div className="bg-white rounded-lg shadow p-4">
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Status</label>
            <select
              value={filters.status}
              onChange={(e) => setFilters({...filters, status: e.target.value})}
              className="w-full border border-gray-300 rounded-md px-3 py-2"
            >
              {isWarehouse ? (
                // Warehouse can only see acknowledged POs
                <>
                  <option value="">All Approved POs</option>
                  <option value="acknowledged">Acknowledged (Ready for GRN)</option>
                </>
              ) : (
                // Admin and Manager can see all statuses
                <>
                  <option value="">All Status</option>
                  <option value="draft">Draft</option>
                  <option value="sent">Sent to Supplier</option>
                  <option value="acknowledged">Acknowledged</option>
                  <option value="partially_received">Partially Received</option>
                  <option value="completed">Completed</option>
                  <option value="cancelled">Cancelled</option>
                </>
              )}
            </select>
          </div>
          
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Type</label>
            <select
              value={filters.type}
              onChange={(e) => setFilters({...filters, type: e.target.value})}
              className="w-full border border-gray-300 rounded-md px-3 py-2"
            >
              <option value="">All Types</option>
              <option value="auto">Auto-Generated</option>
              <option value="manual">Manual</option>
            </select>
          </div>
          
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Supplier</label>
            <select
              value={filters.supplierId}
              onChange={(e) => setFilters({...filters, supplierId: e.target.value})}
              className="w-full border border-gray-300 rounded-md px-3 py-2"
              disabled={filters.type === 'auto'} // Disable for auto-generated POs
            >
              <option value="">All Suppliers</option>
              {suppliers.map(supplier => (
                <option key={supplier.id} value={supplier.id}>
                  {supplier.name}
                </option>
              ))}
            </select>
            {filters.type === 'auto' && (
              <div className="text-xs text-gray-500 mt-1">
                Auto-generated POs use system-selected suppliers
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Purchase Orders Table */}
      <div className="bg-white rounded-lg shadow">
        <div className="p-6">
          <h2 className="text-lg font-semibold mb-4">Purchase Orders</h2>
          
          {loading ? (
            <div className="text-center py-8">Loading purchase orders...</div>
          ) : purchaseOrders.length === 0 ? (
            <div className="text-center py-8 text-gray-500">
              <div className="mx-auto flex items-center justify-center h-12 w-12 rounded-full bg-gray-100 mb-4">
                <svg className="h-6 w-6 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                </svg>
              </div>
              <h3 className="text-lg font-medium text-gray-900 mb-2">No Purchase Orders Found</h3>
              <p className="text-gray-600 mb-4">
                {filters.status || filters.supplierId || filters.type
                  ? 'No purchase orders match your current filters. Try clearing the filters.' 
                  : 'No purchase orders have been created yet. Purchase orders are automatically generated from approved purchase requests.'}
              </p>
              {(filters.status || filters.supplierId || filters.type) && (
                <button
                  onClick={() => setFilters({ status: '', supplierId: '', type: '' })}
                  className="text-blue-600 hover:text-blue-800 text-sm font-medium"
                >
                  Clear All Filters
                </button>
              )}
            </div>
          ) : (
            <div className="overflow-x-auto">
              <table className="min-w-full divide-y divide-gray-200">
                <thead className="bg-gray-50">
                  <tr>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      PO Details
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Item
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Supplier
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Quantity & Amount
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Urgency Level
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Status
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Delivery
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Actions
                    </th>
                  </tr>
                </thead>
                <tbody className="bg-white divide-y divide-gray-200">
                  {purchaseOrders.map((po) => (
                    <tr key={po.id}>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <div className="text-sm font-medium text-gray-900">{po.poNumber}</div>
                        <div className="text-sm text-gray-500">
                          From: {po.purchaseRequest?.prNumber || 'N/A'}
                        </div>
                        <div className="text-sm text-gray-500">
                          {po.isAutoGenerated ? (
                            <span className="inline-flex items-center px-2 py-1 rounded-full text-xs bg-purple-100 text-purple-800">
                              Auto-Generated
                            </span>
                          ) : (
                            <span className="inline-flex items-center px-2 py-1 rounded-full text-xs bg-gray-100 text-gray-800">
                              Manual
                            </span>
                          )}
                        </div>
                        <div className="text-xs text-gray-400 mt-1">
                          Created: {new Date(po.createdAt).toLocaleDateString()}
                        </div>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <div className="text-sm font-medium text-gray-900">{po.item?.name || 'N/A'}</div>
                        <div className="text-sm text-gray-500">{po.item?.sku || 'N/A'}</div>
                        <div className="text-xs text-gray-400">{po.item?.category?.name || 'N/A'}</div>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <div className="text-sm font-medium text-gray-900">{po.supplier?.name || 'N/A'}</div>
                        <div className="text-sm text-gray-500">{po.supplier?.email || 'N/A'}</div>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <div className="text-sm text-gray-900">Qty: {po.orderedQuantity || 0}</div>
                        <div className="text-sm text-gray-500">Unit Price: {po.unitPrice || 0}</div>
                        <div className="text-sm font-medium text-gray-900">Total: {po.totalAmount || 0}</div>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        {po.purchaseRequest?.urgencyLevel && (
                          <div className="mb-1">
                            <div>{getUrgencyBadge(po.purchaseRequest.urgencyLevel)}</div>
                          </div>
                        )}
                        {po.purchaseRequest?.reason && (
                          <div className="text-xs text-gray-500">
                            Reason: {po.purchaseRequest.reason.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase())}
                          </div>
                        )}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        {getStatusBadge(po.status)}
                        {po.sentAt && (
                          <div className="text-xs text-gray-400 mt-1">
                            Sent: {new Date(po.sentAt).toLocaleDateString()}
                          </div>
                        )}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <div className="text-sm text-gray-900">
                          To: {po.warehouse?.name || 'N/A'}
                        </div>
                        <div className="text-sm text-gray-500">
                          Expected: {po.expectedDeliveryDate ? new Date(po.expectedDeliveryDate).toLocaleDateString() : 'TBD'}
                        </div>
                        {po.actualDeliveryDate && (
                          <div className="text-sm text-green-600">
                            Confirmed: {new Date(po.actualDeliveryDate).toLocaleDateString()}
                          </div>
                        )}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm font-medium">
                        <div className="flex space-x-2">
                          <button
                            onClick={() => openDetailsModal(po)}
                            className="text-blue-600 hover:text-blue-900 px-2 py-1 border border-blue-300 rounded text-xs"
                          >
                            View Details
                          </button>
                          
                          {/* Admin-only actions */}
                          {canApprovePO && po.status === 'draft' && (
                            <>
                              <button
                                onClick={() => approvePO(po.id)}
                                className="text-green-600 hover:text-green-900 px-2 py-1 border border-green-300 rounded text-xs"
                              >
                                Approve
                              </button>
                              <button
                                onClick={() => rejectPO(po.id)}
                                className="text-red-600 hover:text-red-900 px-2 py-1 border border-red-300 rounded text-xs"
                              >
                                Reject
                              </button>
                            </>
                          )}
                          
                          {canEditPO && po.status === 'draft' && (
                            <button
                              onClick={() => editPO(po.id)}
                              className="text-yellow-600 hover:text-yellow-900 px-2 py-1 border border-yellow-300 rounded text-xs"
                            >
                              Edit
                            </button>
                          )}
                          
                          {canCancelPO && !['completed', 'cancelled'].includes(po.status) && (
                            <button
                              onClick={() => cancelPO(po.id)}
                              className="text-red-600 hover:text-red-900 px-2 py-1 border border-red-300 rounded text-xs"
                            >
                              Cancel
                            </button>
                          )}

                          {/* Delay approval actions (Admin/Manager only) */}
                          {canApproveDelay && po.status === 'delay_requested' && (
                            <>
                              <button
                                onClick={() => approveDelay(po.id)}
                                className="text-green-600 hover:text-green-900 px-2 py-1 border border-green-300 rounded text-xs"
                              >
                                Approve Delay
                              </button>
                              <button
                                onClick={() => rejectDelay(po.id)}
                                className="text-red-600 hover:text-red-900 px-2 py-1 border border-red-300 rounded text-xs"
                              >
                                Reject Delay
                              </button>
                            </>
                          )}
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>
      </div>

      {/* Details Modal */}
      {showDetailsModal && selectedPO && (
        <div className="fixed inset-0 bg-gray-600 bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-white rounded-lg p-6 w-full max-w-2xl max-h-screen overflow-y-auto">
            <div className="flex justify-between items-center mb-4">
              <h3 className="text-lg font-semibold">Purchase Order Details</h3>
              <button
                onClick={() => setShowDetailsModal(false)}
                className="text-gray-400 hover:text-gray-600"
              >
                <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>
            
            <div className="space-y-6">
              {/* Basic Info */}
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700">PO Number</label>
                  <div className="text-sm text-gray-900">{selectedPO.poNumber}</div>
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700">Status</label>
                  <div>{getStatusBadge(selectedPO.status)}</div>
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700">Type</label>
                  <div>
                    {selectedPO.isAutoGenerated ? (
                      <span className="inline-flex items-center px-2 py-1 rounded-full text-xs bg-purple-100 text-purple-800">
                        Auto-Generated
                      </span>
                    ) : (
                      <span className="inline-flex items-center px-2 py-1 rounded-full text-xs bg-gray-100 text-gray-800">
                        Manual
                      </span>
                    )}
                  </div>
                </div>
              </div>

              {/* Item Details */}
              <div>
                <h4 className="text-md font-medium text-gray-900 mb-2">Item Information</h4>
                <div className="bg-gray-50 p-4 rounded-lg">
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <label className="block text-sm font-medium text-gray-700">Item Name</label>
                      <div className="text-sm text-gray-900">{selectedPO.item?.name || 'N/A'}</div>
                    </div>
                    <div>
                      <label className="block text-sm font-medium text-gray-700">SKU</label>
                      <div className="text-sm text-gray-900">{selectedPO.item?.sku || 'N/A'}</div>
                    </div>
                    <div>
                      <label className="block text-sm font-medium text-gray-700">Category</label>
                      <div className="text-sm text-gray-900">{selectedPO.item?.category?.name || 'N/A'}</div>
                    </div>
                    <div>
                      <label className="block text-sm font-medium text-gray-700">Quantity</label>
                      <div className="text-sm text-gray-900">{selectedPO.orderedQuantity || 0}</div>
                    </div>
                  </div>
                </div>
              </div>

              {/* Supplier Details */}
              <div>
                <h4 className="text-md font-medium text-gray-900 mb-2">Supplier Information</h4>
                <div className="bg-gray-50 p-4 rounded-lg">
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <label className="block text-sm font-medium text-gray-700">Supplier Name</label>
                      <div className="text-sm text-gray-900">{selectedPO.supplier?.name || 'N/A'}</div>
                    </div>
                    <div>
                      <label className="block text-sm font-medium text-gray-700">Email</label>
                      <div className="text-sm text-gray-900">{selectedPO.supplier?.email || 'N/A'}</div>
                    </div>
                  </div>
                </div>
              </div>

              {/* Pricing Details */}
              <div>
                <h4 className="text-md font-medium text-gray-900 mb-2">Pricing Information</h4>
                <div className="bg-gray-50 p-4 rounded-lg">
                  <div className="grid grid-cols-3 gap-4">
                    <div>
                      <label className="block text-sm font-medium text-gray-700">Unit Price</label>
                      <div className="text-sm text-gray-900">{selectedPO.unitPrice || 0}</div>
                    </div>
                    <div>
                      <label className="block text-sm font-medium text-gray-700">Quantity</label>
                      <div className="text-sm text-gray-900">{selectedPO.orderedQuantity || 0}</div>
                    </div>
                    <div>
                      <label className="block text-sm font-medium text-gray-700">Total Amount</label>
                      <div className="text-lg font-medium text-gray-900">{selectedPO.totalAmount || 0}</div>
                    </div>
                  </div>
                </div>
              </div>

              {/* Delivery Details */}
              <div>
                <h4 className="text-md font-medium text-gray-900 mb-2">Delivery Information</h4>
                <div className="bg-gray-50 p-4 rounded-lg">
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <label className="block text-sm font-medium text-gray-700">Delivery Location</label>
                      <div className="text-sm text-gray-900">{selectedPO.warehouse?.name || 'N/A'}</div>
                    </div>
                    <div>
                      <label className="block text-sm font-medium text-gray-700">Expected Delivery</label>
                      <div className="text-sm text-gray-900">
                        {selectedPO.expectedDeliveryDate ? new Date(selectedPO.expectedDeliveryDate).toLocaleDateString() : 'TBD'}
                      </div>
                    </div>
                    {selectedPO.actualDeliveryDate && (
                      <div className="col-span-2">
                        <label className="block text-sm font-medium text-gray-700">Confirmed Delivery</label>
                        <div className="text-sm text-green-600">
                          {new Date(selectedPO.actualDeliveryDate).toLocaleDateString()}
                        </div>
                      </div>
                    )}
                  </div>
                </div>
              </div>

              {/* Timeline */}
              <div>
                <h4 className="text-md font-medium text-gray-900 mb-2">Timeline</h4>
                <div className="bg-gray-50 p-4 rounded-lg">
                  <div className="space-y-2">
                    <div className="flex justify-between">
                      <span className="text-sm text-gray-700">Created:</span>
                      <span className="text-sm text-gray-900">{new Date(selectedPO.createdAt).toLocaleString()}</span>
                    </div>
                    {selectedPO.sentAt && (
                      <div className="flex justify-between">
                        <span className="text-sm text-gray-700">Sent to Supplier:</span>
                        <span className="text-sm text-gray-900">{new Date(selectedPO.sentAt).toLocaleString()}</span>
                      </div>
                    )}
                    <div className="flex justify-between">
                      <span className="text-sm text-gray-700">Created By:</span>
                      <span className="text-sm text-gray-900">{selectedPO.createdBy?.name || 'N/A'}</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            
            <div className="flex justify-end mt-6">
              <button
                onClick={() => setShowDetailsModal(false)}
                className="px-4 py-2 bg-gray-600 text-white rounded-md hover:bg-gray-700"
              >
                Close
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Edit Modal */}
      {showEditModal && selectedPO && (
        <div className="fixed inset-0 bg-gray-600 bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-white rounded-lg p-6 w-full max-w-md">
            <div className="flex justify-between items-center mb-4">
              <h3 className="text-lg font-semibold">Edit Purchase Order</h3>
              <button
                onClick={() => setShowEditModal(false)}
                className="text-gray-400 hover:text-gray-600"
              >
                <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>
            
            <div className="mb-4 p-3 bg-gray-50 rounded">
              <div className="text-sm font-medium">{selectedPO.poNumber}</div>
              <div className="text-sm text-gray-600">{selectedPO.item?.name}</div>
              <div className="text-sm text-gray-600">Status: {selectedPO.status}</div>
            </div>
            
            <form onSubmit={handleEditSubmit} className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Ordered Quantity *</label>
                <input
                  type="number"
                  min="1"
                  value={editForm.orderedQuantity}
                  onChange={(e) => setEditForm({...editForm, orderedQuantity: e.target.value})}
                  className="w-full border border-gray-300 rounded-md px-3 py-2"
                  required
                />
              </div>
              
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Unit Price *</label>
                <input
                  type="number"
                  step="0.01"
                  min="0"
                  value={editForm.unitPrice}
                  onChange={(e) => setEditForm({...editForm, unitPrice: e.target.value})}
                  className="w-full border border-gray-300 rounded-md px-3 py-2"
                  required
                />
              </div>
              
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Expected Delivery Date</label>
                <input
                  type="date"
                  value={editForm.expectedDeliveryDate}
                  onChange={(e) => setEditForm({...editForm, expectedDeliveryDate: e.target.value})}
                  className="w-full border border-gray-300 rounded-md px-3 py-2"
                />
              </div>
              
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Notes</label>
                <textarea
                  value={editForm.notes}
                  onChange={(e) => setEditForm({...editForm, notes: e.target.value})}
                  className="w-full border border-gray-300 rounded-md px-3 py-2"
                  rows="3"
                  placeholder="Additional notes..."
                />
              </div>
              
              <div className="flex justify-end space-x-3 mt-6">
                <button
                  type="button"
                  onClick={() => setShowEditModal(false)}
                  className="px-4 py-2 border border-gray-300 rounded-md text-gray-700 hover:bg-gray-50"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={loading}
                  className="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 disabled:opacity-50"
                >
                  {loading ? 'Updating...' : 'Update PO'}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};

export default PurchaseOrder;