import { useState, useEffect, useContext } from 'react';
import { AuthContext } from '../context/AuthContext';
import { purchaseRequestApi } from '../api/purchaseRequestApi';
import { itemApi } from '../api/itemApi';
import { warehouseApi } from '../api/warehouseApi';
import { fetchSuppliers } from '../api/supplierApi';

const PurchaseRequest = () => {
  const { user } = useContext(AuthContext);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');

  // Data states
  const [purchaseRequests, setPurchaseRequests] = useState([]);
  const [items, setItems] = useState([]);
  const [warehouses, setWarehouses] = useState([]);
  const [suppliers, setSuppliers] = useState([]);
  const [availableSuppliers, setAvailableSuppliers] = useState([]); // Suppliers for selected item

  // Filters
  const [filters, setFilters] = useState({
    status: '',
    urgency: '',
    isAutoGenerated: ''
  });

  // Modal states
  const [showCreateModal, setShowCreateModal] = useState(false);
  const [showApprovalModal, setShowApprovalModal] = useState(false);
  const [selectedPR, setSelectedPR] = useState(null);

  // Form state
  const [prForm, setPrForm] = useState({
    itemId: '',
    warehouseId: '',
    requestedQuantity: '',
    urgencyLevel: 'medium',
    reason: 'manual_request',
    notes: '',
    preferredSupplierId: '' // Add supplier selection
  });

  const [approvalForm, setApprovalForm] = useState({
    action: '',
    notes: ''
  });

  const isAdmin = user?.role === 'admin';
  const isManager = user?.role === 'manager';
  const isWarehouse = user?.role === 'warehouse';
  
  // Access levels based on backend response
  const [accessLevel, setAccessLevel] = useState('none');
  
  // Determine user capabilities based on CORRECT IMRAS roles
  const canCreatePR = isManager; // ✅ ONLY Manager creates PRs (not Admin)
  const canEditPR = isManager; // ✅ ONLY Manager edits PRs (not Admin)
  const canDeletePR = isManager; // ✅ ONLY Manager deletes PRs (not Admin)
  const canConvertToPO = isManager; // ✅ ONLY Manager converts PR to PO (not Admin)
  const isReadOnly = isWarehouse || isAdmin; // ✅ Warehouse + Admin are read-only
  const hasOverrideAccess = isAdmin; // ✅ Admin has emergency override only

  // Load data on component mount
  useEffect(() => {
    console.log('🚀 PR Component mounted, user:', user);
    loadPurchaseRequests();
    // Load items and warehouses for all roles (needed for viewing PR details)
    loadItems();
    loadWarehouses();
    loadSuppliers();
    
    // Test database connectivity
    testDatabaseConnection();
  }, [filters]);

  const testDatabaseConnection = async () => {
    try {
      console.log('🧪 Testing database connection...');
      const response = await purchaseRequestApi.testConnection();
      console.log('🧪 Database test result:', response);
    } catch (err) {
      console.error('🧪 Database test failed:', err);
    }
  };

  const loadPurchaseRequests = async () => {
    setLoading(true);
    try {
      console.log('Loading purchase requests with filters:', filters);
      const response = await purchaseRequestApi.getAll(filters);
      console.log('Purchase requests response:', response);
      
      if (response.success) {
        setPurchaseRequests(response.data || []);
        setAccessLevel(response.accessLevel || 'none');
        console.log('Purchase requests loaded:', response.data?.length || 0);
        console.log('Access level:', response.accessLevel);
      } else {
        setError('Failed to load purchase requests: ' + (response.message || 'Unknown error'));
        setPurchaseRequests([]);
      }
    } catch (err) {
      console.error('Load purchase requests error:', err);
      setError('Failed to load purchase requests: ' + (err.response?.data?.message || err.message || 'Unknown error'));
      setPurchaseRequests([]);
    } finally {
      setLoading(false);
    }
  };

  const loadItems = async () => {
    try {
      console.log('🔍 Loading items...');
      const response = await itemApi.getAll();
      console.log('📦 Items API response:', response);
      
      // Handle the correct API response format from item controller
      if (response.data) {
        // API returns: { items: [...], totalItems: n, totalPages: n, currentPage: n }
        const items = response.data.items || [];
        setItems(items);
        console.log('✅ Items loaded:', items.length);
      } else {
        // Direct response format
        const items = response.items || response || [];
        setItems(items);
        console.log('✅ Items loaded (direct):', items.length);
      }
    } catch (err) {
      console.error('❌ Failed to load items:', err);
      setError('Failed to load items: ' + (err.response?.data?.message || err.message));
      setItems([]);
    }
  };

  const loadWarehouses = async () => {
    try {
      console.log('🏢 Loading warehouses...');
      const response = await warehouseApi.getAll();
      console.log('🏢 Warehouses API response:', response);
      
      // Handle the correct API response format from warehouse controller
      if (response.data) {
        // API returns direct array of warehouses
        const warehouses = Array.isArray(response.data) ? response.data : [];
        setWarehouses(warehouses);
        console.log('✅ Warehouses loaded:', warehouses.length);
      } else {
        // Direct array response
        const warehouses = Array.isArray(response) ? response : [];
        setWarehouses(warehouses);
        console.log('✅ Warehouses loaded (direct):', warehouses.length);
      }
    } catch (err) {
      console.error('❌ Failed to load warehouses:', err);
      setError('Failed to load warehouses: ' + (err.response?.data?.message || err.message));
      setWarehouses([]);
    }
  };

  const loadSuppliers = async () => {
    try {
      console.log('🏪 Loading suppliers...');
      const response = await fetchSuppliers();
      console.log('🏪 Suppliers API response:', response);
      
      // Handle the correct API response format from supplier controller
      if (response.data) {
        // API returns direct array of suppliers
        const suppliers = Array.isArray(response.data) ? response.data : [];
        setSuppliers(suppliers);
        console.log('✅ Suppliers loaded:', suppliers.length);
      } else {
        // Direct array response
        const suppliers = Array.isArray(response) ? response : [];
        setSuppliers(suppliers);
        console.log('✅ Suppliers loaded (direct):', suppliers.length);
      }
    } catch (err) {
      console.error('❌ Failed to load suppliers:', err);
      setError('Failed to load suppliers: ' + (err.response?.data?.message || err.message));
      setSuppliers([]);
    }
  };

  const loadSuppliersForItem = async (itemId) => {
    // Show all suppliers, but highlight item's preferred supplier
    setAvailableSuppliers(suppliers);
    
    // If item has preferred supplier, auto-select it
    if (itemId && items.length > 0) {
      const selectedItem = items.find(item => item.id === parseInt(itemId));
      if (selectedItem?.preferredSupplierId && !prForm.preferredSupplierId) {
        setPrForm(prev => ({
          ...prev,
          preferredSupplierId: selectedItem.preferredSupplierId.toString()
        }));
      }
    }
  };

  // Load suppliers when item is selected
  useEffect(() => {
    if (prForm.itemId) {
      loadSuppliersForItem(prForm.itemId);
    } else {
      setAvailableSuppliers(suppliers);
    }
  }, [prForm.itemId, suppliers, items]);

  // Clear messages
  useEffect(() => {
    if (error || success) {
      const timer = setTimeout(() => {
        setError('');
        setSuccess('');
      }, 5000);
      return () => clearTimeout(timer);
    }
  }, [error, success]);

  const handleCreateSubmit = async (e) => {
    e.preventDefault();
    
    console.log('🚀 Submitting PR form:', prForm);
    
    if (!prForm.itemId || !prForm.warehouseId || !prForm.requestedQuantity) {
      setError('Please fill in all required fields');
      return;
    }

    try {
      setLoading(true);
      setError(''); // Clear previous errors
      
      const prData = {
        itemId: parseInt(prForm.itemId),
        warehouseId: parseInt(prForm.warehouseId),
        requestedQuantity: parseInt(prForm.requestedQuantity),
        urgencyLevel: prForm.urgencyLevel,
        reason: prForm.reason,
        notes: prForm.notes,
        preferredSupplierId: prForm.preferredSupplierId ? parseInt(prForm.preferredSupplierId) : null
      };

      console.log('📤 Sending PR data:', prData);

      let response;
      if (selectedPR) {
        // Edit mode
        console.log('✏️ Editing PR:', selectedPR.id);
        response = await purchaseRequestApi.edit(selectedPR.id, prData);
      } else {
        // Create mode
        console.log('➕ Creating new PR');
        response = await purchaseRequestApi.create(prData);
      }
      
      console.log('📥 API Response:', response);
      
      if (response.success) {
        setSuccess(selectedPR ? 'Purchase request updated successfully' : 'Purchase request created successfully');
        setShowCreateModal(false);
        setSelectedPR(null);
        setPrForm({
          itemId: '',
          warehouseId: '',
          requestedQuantity: '',
          urgencyLevel: 'medium',
          reason: 'manual_request',
          notes: '',
          preferredSupplierId: ''
        });
        
        // Refresh the list, but don't show error if refresh fails
        try {
          await loadPurchaseRequests();
        } catch (refreshError) {
          console.warn('⚠️ Failed to refresh PR list, but PR was created successfully:', refreshError);
          // Don't set error state here since the main operation succeeded
        }
      } else {
        const errorMsg = response.message || response.error || 'Unknown error occurred';
        setError(selectedPR ? `Failed to update purchase request: ${errorMsg}` : `Failed to create purchase request: ${errorMsg}`);
        console.error('❌ API Error:', response);
      }
    } catch (err) {
      console.error('❌ Request Error:', err);
      console.error('Error details:', {
        message: err.message,
        response: err.response?.data,
        status: err.response?.status
      });
      
      const errorMessage = err.response?.data?.message || err.response?.data?.error || err.message || 'Unknown error';
      setError((selectedPR ? 'Failed to update purchase request: ' : 'Failed to create purchase request: ') + errorMessage);
    } finally {
      setLoading(false);
    }
  };

  const handleApprovalSubmit = async (e) => {
    e.preventDefault();
    
    if (!approvalForm.action) {
      setError('Please select an action');
      return;
    }

    try {
      setLoading(true);
      
      const response = await purchaseRequestApi.updateStatus(selectedPR.id, {
        action: approvalForm.action,
        notes: approvalForm.notes
      });
      
      if (response.success) {
        setSuccess(`Purchase request ${approvalForm.action}d successfully`);
        setShowApprovalModal(false);
        setSelectedPR(null);
        setApprovalForm({ action: '', notes: '' });
        
        await loadPurchaseRequests();
      } else {
        setError('Failed to process approval');
      }
    } catch (err) {
      setError('Failed to process approval: ' + (err.response?.data?.message || err.message || 'Unknown error'));
    } finally {
      setLoading(false);
    }
  };

  const openApprovalModal = (pr) => {
    setSelectedPR(pr);
    setApprovalForm({ action: '', notes: '' });
    setShowApprovalModal(true);
  };

  const openEditModal = (pr) => {
    setSelectedPR(pr);
    setPrForm({
      itemId: pr.itemId.toString(),
      warehouseId: pr.warehouseId.toString(),
      requestedQuantity: pr.requestedQuantity.toString(),
      urgencyLevel: pr.urgencyLevel,
      reason: pr.reason,
      notes: pr.notes || '',
      preferredSupplierId: pr.preferredSupplierId ? pr.preferredSupplierId.toString() : ''
    });
    setShowCreateModal(true); // Reuse create modal for editing
  };

  const handleCreatePOFromPR = async (prId) => {
    try {
      setLoading(true);
      
      const response = await purchaseRequestApi.createPOFromPR(prId);
      
      if (response.success) {
        setSuccess('Purchase order created successfully. PR remains pending for approval.');
        await loadPurchaseRequests();
      } else {
        setError('Failed to create PO from PR');
      }
    } catch (err) {
      setError('Failed to create PO: ' + (err.response?.data?.message || err.message || 'Unknown error'));
    } finally {
      setLoading(false);
    }
  };

  const closeCreateModal = () => {
    setShowCreateModal(false);
    setSelectedPR(null);
    setPrForm({
      itemId: '',
      warehouseId: '',
      requestedQuantity: '',
      urgencyLevel: 'medium',
      reason: 'manual_request',
      notes: '',
      preferredSupplierId: ''
    });
  };

  const getStatusBadge = (status) => {
    const statusConfig = {
      'pending': { color: 'bg-yellow-100 text-yellow-800', text: 'Pending' },
      'approved': { color: 'bg-green-100 text-green-800', text: 'Approved' },
      'rejected': { color: 'bg-red-100 text-red-800', text: 'Rejected' },
      'converted_to_po': { color: 'bg-blue-100 text-blue-800', text: 'Converted to PO' }
    };

    const config = statusConfig[status] || { color: 'bg-gray-100 text-gray-800', text: status };
    
    return (
      <span className={`inline-flex px-2 py-1 text-xs font-semibold rounded-full ${config.color}`}>
        {config.text}
      </span>
    );
  };

  const getUrgencyBadge = (urgency) => {
    const urgencyConfig = {
      'low': { color: 'bg-gray-100 text-gray-800', text: 'Low' },
      'medium': { color: 'bg-blue-100 text-blue-800', text: 'Medium' },
      'high': { color: 'bg-orange-100 text-orange-800', text: 'High' },
      'urgent': { color: 'bg-red-100 text-red-800', text: 'Urgent' }
    };

    const config = urgencyConfig[urgency] || { color: 'bg-gray-100 text-gray-800', text: urgency };
    
    return (
      <span className={`inline-flex px-2 py-1 text-xs font-semibold rounded-full ${config.color}`}>
        {config.text}
      </span>
    );
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex justify-between items-center">
        <h1 className="text-2xl font-bold text-gray-900">Purchase Requests</h1>
        
        <div className="flex items-center space-x-4">
          {/* Role-based header info */}
          {/* Role-based messages removed */}
          
          {/* Create button - ONLY for Manager */}
          {canCreatePR && (
            <button
              onClick={() => setShowCreateModal(true)}
              className="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700"
            >
              Create Purchase Request
            </button>
          )}
          
          {/* Admin Override Button (Emergency Only) */}
          {hasOverrideAccess && !canCreatePR && (
            <button
              onClick={() => {
                const reason = prompt('Admin Override Reason (Required):');
                if (reason) {
                  console.log(`🚨 Admin Override: ${user.name} - Reason: ${reason}`);
                  setShowCreateModal(true);
                }
              }}
              className="px-4 py-2 bg-red-600 text-white rounded-md hover:bg-red-700 border-2 border-red-400"
              title="Emergency Override - Requires Reason"
            >
              🚨 Override Create PR
            </button>
          )}
        </div>
      </div>

      {/* Messages */}
      {error && (
        <div className="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded">
          {error}
        </div>
      )}
      {success && (
        <div className="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded">
          {success}
        </div>
      )}

      {/* Filters */}
      <div className="bg-white rounded-lg shadow p-4">
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Status</label>
            <select
              value={filters.status}
              onChange={(e) => setFilters({...filters, status: e.target.value})}
              className="w-full border border-gray-300 rounded-md px-3 py-2"
            >
              <option value="">All Status</option>
              <option value="pending">Pending</option>
              <option value="approved">Approved</option>
              <option value="rejected">Rejected</option>
              <option value="converted_to_po">Converted to PO</option>
            </select>
          </div>
          
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Urgency</label>
            <select
              value={filters.urgency}
              onChange={(e) => setFilters({...filters, urgency: e.target.value})}
              className="w-full border border-gray-300 rounded-md px-3 py-2"
            >
              <option value="">All Urgency</option>
              <option value="low">Low</option>
              <option value="medium">Medium</option>
              <option value="high">High</option>
              <option value="urgent">Urgent</option>
            </select>
          </div>
          
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Type</label>
            <select
              value={filters.isAutoGenerated}
              onChange={(e) => setFilters({...filters, isAutoGenerated: e.target.value})}
              className="w-full border border-gray-300 rounded-md px-3 py-2"
            >
              <option value="">All Types</option>
              <option value="true">Auto-Generated</option>
              <option value="false">Manual</option>
            </select>
          </div>
        </div>
      </div>

      {/* Purchase Requests Table */}
      <div className="bg-white rounded-lg shadow">
        <div className="p-6">
          <h2 className="text-lg font-semibold mb-4">Purchase Requests</h2>
          
          {loading ? (
            <div className="text-center py-8">Loading purchase requests...</div>
          ) : purchaseRequests.length === 0 ? (
            <div className="text-center py-8 text-gray-500">
              No purchase requests found.
            </div>
          ) : (
            <div className="overflow-x-auto">
              <table className="min-w-full divide-y divide-gray-200">
                <thead className="bg-gray-50">
                  <tr>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      PR Details
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Item
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Quantity
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Supplier
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Urgency
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Status
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Requested By
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Actions
                    </th>
                  </tr>
                </thead>
                <tbody className="bg-white divide-y divide-gray-200">
                  {purchaseRequests.map((pr) => (
                    <tr key={pr.id}>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <div className="text-sm font-medium text-gray-900">{pr.prNumber}</div>
                        <div className="text-sm text-gray-500">
                          {pr.isAutoGenerated ? (
                            <span className="inline-flex items-center px-2 py-1 rounded-full text-xs bg-purple-100 text-purple-800">
                              Auto-Generated
                            </span>
                          ) : (
                            <span className="inline-flex items-center px-2 py-1 rounded-full text-xs bg-gray-100 text-gray-800">
                              Manual
                            </span>
                          )}
                        </div>
                        <div className="text-xs text-gray-400 mt-1">
                          {new Date(pr.createdAt).toLocaleDateString()}
                        </div>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <div className="text-sm font-medium text-gray-900">{pr.item.name}</div>
                        <div className="text-sm text-gray-500">{pr.item.sku}</div>
                        <div className="text-xs text-gray-400">{pr.item.category.name}</div>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <div className="text-sm text-gray-900">{pr.requestedQuantity}</div>
                        <div className="text-sm text-gray-500">To: {pr.warehouse.name}</div>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        {pr.preferredSupplier ? (
                          <div>
                            <div className="text-sm font-medium text-gray-900">{pr.preferredSupplier.name}</div>
                            <div className="text-sm text-gray-500">{pr.preferredSupplier.email}</div>
                          </div>
                        ) : (
                          <div className="text-sm text-gray-500 italic">Auto-select</div>
                        )}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        {getUrgencyBadge(pr.urgencyLevel)}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        {getStatusBadge(pr.status)}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <div className="text-sm text-gray-900">{pr.requestedBy.name}</div>
                        <div className="text-sm text-gray-500">{pr.requestedBy.email}</div>
                        {pr.approvedBy && (
                          <div className="text-xs text-green-600 mt-1">
                            Approved by: {pr.approvedBy.name}
                          </div>
                        )}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm font-medium">
                        {pr.status === 'pending' && canConvertToPO ? (
                          <div className="flex space-x-2">
                            <button
                              onClick={() => handleCreatePOFromPR(pr.id)}
                              className="text-blue-600 hover:text-blue-900 px-3 py-1 border border-blue-300 rounded text-sm"
                              disabled={loading}
                            >
                              {loading ? 'Creating PO...' : 'Create PO'}
                            </button>
                            {canEditPR && (
                              <button
                                onClick={() => openEditModal(pr)}
                                className="text-green-600 hover:text-green-900 px-3 py-1 border border-green-300 rounded text-sm"
                              >
                                Edit
                              </button>
                            )}
                          </div>
                        ) : pr.status === 'pending' && hasOverrideAccess && !canConvertToPO ? (
                          <div className="flex space-x-2">
                            <button
                              onClick={() => {
                                const reason = prompt('Admin Override Reason:');
                                if (reason) {
                                  console.log(`🚨 Admin Override PO Creation: ${user.name} - Reason: ${reason}`);
                                  handleCreatePOFromPR(pr.id);
                                }
                              }}
                              className="text-red-600 hover:text-red-900 px-3 py-1 border border-red-300 rounded text-sm"
                              title="Emergency Override"
                            >
                              🚨 Override Create PO
                            </button>
                          </div>
                        ) : pr.status === 'pending' && isReadOnly ? (
                          <span className="text-gray-500 text-sm">Pending Manager Action</span>
                        ) : pr.status === 'approved' ? (
                          <span className="text-green-600 text-sm">✅ Approved</span>
                        ) : pr.status === 'rejected' ? (
                          <span className="text-red-600 text-sm">❌ Rejected</span>
                        ) : pr.status === 'converted_to_po' ? (
                          <span className="text-blue-600 text-sm">🔄 Converted to PO</span>
                        ) : (
                          <span className="text-gray-500 text-sm">No actions available</span>
                        )}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>
      </div>

      {/* Create PR Modal */}
      {showCreateModal && (
        <div className="fixed inset-0 bg-gray-600 bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-white rounded-lg p-6 w-full max-w-md max-h-screen overflow-y-auto">
            <h3 className="text-lg font-semibold mb-4">
              {selectedPR ? 'Edit Purchase Request' : 'Create Purchase Request'}
            </h3>
            
            <form onSubmit={handleCreateSubmit} className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Item *</label>
                <select
                  value={prForm.itemId}
                  onChange={(e) => {
                    console.log('Selected item ID:', e.target.value);
                    setPrForm({...prForm, itemId: e.target.value, preferredSupplierId: ''}); // Reset supplier when item changes
                  }}
                  className="w-full border border-gray-300 rounded-md px-3 py-2"
                  required
                >
                  <option value="">Select Item</option>
                  {items.map(item => (
                    <option key={item.id} value={item.id}>
                      {item.name} ({item.sku})
                    </option>
                  ))}
                </select>
                {items.length === 0 && (
                  <div className="text-red-500 text-xs mt-1">No items available. Please add items first.</div>
                )}
              </div>
              
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Warehouse *</label>
                <select
                  value={prForm.warehouseId}
                  onChange={(e) => {
                    console.log('Selected warehouse ID:', e.target.value);
                    setPrForm({...prForm, warehouseId: e.target.value});
                  }}
                  className="w-full border border-gray-300 rounded-md px-3 py-2"
                  required
                >
                  <option value="">Select Warehouse</option>
                  {warehouses.map(warehouse => (
                    <option key={warehouse.id} value={warehouse.id}>
                      {warehouse.name} ({warehouse.code})
                    </option>
                  ))}
                </select>
                {warehouses.length === 0 && (
                  <div className="text-red-500 text-xs mt-1">No warehouses available. Please add warehouses first.</div>
                )}
              </div>
              
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Preferred Supplier</label>
                <select
                  value={prForm.preferredSupplierId}
                  onChange={(e) => {
                    console.log('Selected supplier ID:', e.target.value);
                    setPrForm({...prForm, preferredSupplierId: e.target.value});
                  }}
                  className="w-full border border-gray-300 rounded-md px-3 py-2"
                >
                  <option value="">Auto-select best supplier</option>
                  {availableSuppliers.map(supplier => (
                    <option key={supplier.id} value={supplier.id}>
                      {supplier.name} - {supplier.email} (Lead time: {supplier.leadTimeDays} days)
                    </option>
                  ))}
                </select>
                {availableSuppliers.length === 0 && (
                  <div className="text-yellow-500 text-xs mt-1">No suppliers available. Please add suppliers first.</div>
                )}
                <div className="text-xs text-gray-500 mt-1">
                  Leave blank to let system choose supplier with best lead time
                </div>
              </div>
              
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Quantity *</label>
                <input
                  type="number"
                  min="1"
                  value={prForm.requestedQuantity}
                  onChange={(e) => setPrForm({...prForm, requestedQuantity: e.target.value})}
                  className="w-full border border-gray-300 rounded-md px-3 py-2"
                  required
                />
              </div>
              
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Urgency Level</label>
                <select
                  value={prForm.urgencyLevel}
                  onChange={(e) => setPrForm({...prForm, urgencyLevel: e.target.value})}
                  className="w-full border border-gray-300 rounded-md px-3 py-2"
                >
                  <option value="low">Low</option>
                  <option value="medium">Medium</option>
                  <option value="high">High</option>
                  <option value="urgent">Urgent</option>
                </select>
              </div>
              
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Reason</label>
                <select
                  value={prForm.reason}
                  onChange={(e) => setPrForm({...prForm, reason: e.target.value})}
                  className="w-full border border-gray-300 rounded-md px-3 py-2"
                >
                  <option value="manual_request">Manual Request</option>
                  <option value="low_stock">Low Stock</option>
                  <option value="out_of_stock">Out of Stock</option>
                  <option value="new_requirement">New Requirement</option>
                </select>
              </div>
              
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Notes</label>
                <textarea
                  value={prForm.notes}
                  onChange={(e) => setPrForm({...prForm, notes: e.target.value})}
                  className="w-full border border-gray-300 rounded-md px-3 py-2"
                  rows="3"
                  placeholder="Additional notes or justification..."
                />
              </div>
              
              <div className="flex justify-end space-x-3 mt-6">
                <button
                  type="button"
                  onClick={closeCreateModal}
                  className="px-4 py-2 border border-gray-300 rounded-md text-gray-700 hover:bg-gray-50"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={loading}
                  className="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 disabled:opacity-50"
                >
                  {loading ? (selectedPR ? 'Updating...' : 'Creating...') : (selectedPR ? 'Update Request' : 'Create Request')}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Approval Modal */}
      {showApprovalModal && selectedPR && (
        <div className="fixed inset-0 bg-gray-600 bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-white rounded-lg p-6 w-full max-w-md">
            <h3 className="text-lg font-semibold mb-4">Review Purchase Request</h3>
            
            <div className="mb-4 p-3 bg-gray-50 rounded">
              <div className="text-sm font-medium">{selectedPR.prNumber}</div>
              <div className="text-sm text-gray-600">{selectedPR.item.name}</div>
              <div className="text-sm text-gray-600">Quantity: {selectedPR.requestedQuantity}</div>
              <div className="text-sm text-gray-600">Urgency: {selectedPR.urgencyLevel}</div>
            </div>
            
            <form onSubmit={handleApprovalSubmit} className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Action *</label>
                <select
                  value={approvalForm.action}
                  onChange={(e) => setApprovalForm({...approvalForm, action: e.target.value})}
                  className="w-full border border-gray-300 rounded-md px-3 py-2"
                  required
                >
                  <option value="">Select Action</option>
                  <option value="approve">Approve</option>
                  <option value="reject">Reject</option>
                </select>
              </div>
              
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Notes</label>
                <textarea
                  value={approvalForm.notes}
                  onChange={(e) => setApprovalForm({...approvalForm, notes: e.target.value})}
                  className="w-full border border-gray-300 rounded-md px-3 py-2"
                  rows="3"
                  placeholder="Approval/rejection notes..."
                />
              </div>
              
              <div className="flex justify-end space-x-3 mt-6">
                <button
                  type="button"
                  onClick={() => setShowApprovalModal(false)}
                  className="px-4 py-2 border border-gray-300 rounded-md text-gray-700 hover:bg-gray-50"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={loading}
                  className={`px-4 py-2 rounded-md text-white font-medium disabled:opacity-50 ${
                    approvalForm.action === 'approve' ? 'bg-green-600 hover:bg-green-700' : 'bg-red-600 hover:bg-red-700'
                  }`}
                >
                  {loading ? 'Processing...' : (approvalForm.action === 'approve' ? 'Approve' : 'Reject')}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};

export default PurchaseRequest;